version: "2"
services:
    mongo:
        image: mongo:4.4.5
        container_name: mongo
        restart: always
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        volumes:
        - /home/vagrant/mongo:/data/db:rw
        ports:
            - 27017:27017
    mongo-express:
        image: mongo-express:0.54.0
        container_name: mongoexpress
        restart: always
        ports:
          - 3002:8081
        environment:
          ME_CONFIG_MONGODB_ADMINUSERNAME: root
          ME_CONFIG_MONGODB_ADMINPASSWORD: example
                